/* eslint-disable @typescript-eslint/no-explicit-any */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useRef, useState } from 'react'
import useSWR from 'swr'
import axios from 'axios'

interface SortInterface {
    [key: string]: string
}

const Collection: NextPage = () => {
    const [data, setData] = useState<any>([])
    const router = useRouter()
    const [isLoading, setLoading] = useState(true)
    const [hasMore, setHasMore] = useState(true)
    const [url, setUrl] = useState('')
    const [page, setPage] = useState(0)
    const [searchTerm, setSearchTerm] = useState('')
    const [sorts, setSorts] = useState<SortInterface>({
        floor: 'none',
        total: 'none',
        day: 'none',
        dayPercent: 'none',
    })


    const timer = useRef<any>(null)
    const perPage = 12

    const fetcher = (servicUrl: RequestInfo) =>
        fetch(servicUrl)
            .then((res) => res.json())
            .then((res) => {
                if (res.collections && res.collections.length > 0) {
                    if (page == 0) {
                        setData(res.collections)
                    } else {
                        setData([...data, ...res.collections])
                    }

                    setHasMore(res.hasMore)
                }

                setLoading(false)
            })

    useSWR(isLoading ? url : null, fetcher)

    useEffect(() => {
        clearTimeout(timer.current)
        timer.current = setTimeout(() => {
            setUrl(
                process.env.NEXT_PUBLIC_SERVER_URL +
                    'api/collections?perPage=' +
                    perPage +
                    '&page=' +
                    page.toString() +
                    '&searchTerm=' +
                    searchTerm +
                    '&sorts=' +
                    JSON.stringify(sorts)
            )

            setLoading(true)

            clearTimeout(timer.current)
        }, 500)
    }, [page, searchTerm, sorts])

    const loadMoreHandler = () => {
        if (hasMore) {
            setPage(page + 1)
        }
    }

    const goToCollection = (addrs: string) => {
        router.push('/collection/' + addrs)
    }

    const searchInputChangeHandler = (
        e: React.ChangeEvent<HTMLInputElement>
    ) => {
        const val = e.target.value
        setSearchTerm(val)
        setPage(0)
    }

    const sortHandler = (sort: string, direction: string) => {
        const temp: SortInterface = {}

        for (const key in sorts) {
            if (key == sort) {
                if (sorts[key] == 'none') {
                    temp[key] = direction
                } else if (direction == 'ascending') {
                    temp[key] = 'descending'
                } else if (direction == 'descending') {
                    temp[key] = 'none'
                }
            } else {
                temp[key] = 'none'
            }
        }

        setSorts(temp)
        setPage(0)
    }

    return (
        <div>
            <Head>
                <title>Jaypigs collections page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="my-8 min-h-screen">
                <div className="container px-4">
                    <h1 className="mb-10 text-[4rem]">Collections</h1>
                    <p>
                        The top NFT collections on Jaypigs, ranked by floor
                        price, volume and other statistics.
                    </p>
                </div>
                <hr className="mt-16 mb-8 border-dark-100 dark:border-dark-400" />
                <div className="container overflow-auto px-4 text-center">
                    <table className="mb-8 min-w-full  text-left">
                        <thead className="">
                            <tr>
                                <th className="w-[40%] py-4 pr-6" colSpan={2}>
                                    <div className="relative text-gray-600 focus-within:text-gray-400">
                                        <span className="absolute inset-y-0 left-0 flex items-center pl-2">
                                            <button
                                                type="submit"
                                                className="focus:shadow-outline p-1 text-dark-100 focus:outline-none"
                                            >
                                                <svg
                                                    fill="none"
                                                    stroke="currentColor"
                                                    strokeLinecap="round"
                                                    strokeLinejoin="round"
                                                    strokeWidth="2"
                                                    viewBox="0 0 24 24"
                                                    className="h-6 w-6"
                                                >
                                                    <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                                                </svg>
                                            </button>
                                        </span>
                                        <input
                                            type="search"
                                            name="q"
                                            className="text-md h-12 w-full border border-dark-100 py-2 pl-10 text-dark-400 placeholder-dark-100 shadow-none focus:border-dark-400 focus:shadow-none focus:outline-none focus:ring-transparent dark:border-dark-400 dark:bg-dark-400 dark:text-white"
                                            placeholder="Search..."
                                            autoComplete="off"
                                            value={searchTerm}
                                            onChange={searchInputChangeHandler}
                                        />
                                    </div>
                                </th>
                                <th className="w-[15%] px-6 py-4">
                                    <div className="flex items-center">
                                        Floor
                                        <div className="ml-2 flex flex-col items-center">
                                            {(sorts.floor == 'none' ||
                                                sorts.floor == 'ascending') && (
                                                <svg
                                                    viewBox="0 0 32 32"
                                                    focusable="false"
                                                    className="h-3 w-3 cursor-pointer"
                                                    onClick={() =>
                                                        sortHandler(
                                                            'floor',
                                                            'ascending'
                                                        )
                                                    }
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        clipRule="evenodd"
                                                        d="M16 10L26 20L24.6 21.4L16 12.8L7.4 21.4L6 20L16 10Z"
                                                        fill="currentColor"
                                                    ></path>
                                                </svg>
                                            )}
                                            {(sorts.floor == 'none' ||
                                                sorts.floor ==
                                                    'descending') && (
                                                <svg
                                                    viewBox="0 0 32 32"
                                                    focusable="false"
                                                    className="h-3 w-3 cursor-pointer"
                                                    onClick={() =>
                                                        sortHandler(
                                                            'floor',
                                                            'descending'
                                                        )
                                                    }
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        clipRule="evenodd"
                                                        d="M16 22L6 12L7.4 10.6L16 19.2L24.6 10.6L26 12L16 22Z"
                                                        fill="currentColor"
                                                    ></path>
                                                </svg>
                                            )}
                                        </div>
                                    </div>
                                </th>
                                <th className="w-[15%] px-6 py-4">
                                    <div className="flex items-center">
                                        Totoal Vol
                                        <div className="ml-2 flex flex-col items-center">
                                            {(sorts.total == 'none' ||
                                                sorts.total == 'ascending') && (
                                                <svg
                                                    viewBox="0 0 32 32"
                                                    focusable="false"
                                                    className="h-3 w-3 cursor-pointer"
                                                    onClick={() =>
                                                        sortHandler(
                                                            'total',
                                                            'ascending'
                                                        )
                                                    }
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        clipRule="evenodd"
                                                        d="M16 10L26 20L24.6 21.4L16 12.8L7.4 21.4L6 20L16 10Z"
                                                        fill="currentColor"
                                                    ></path>
                                                </svg>
                                            )}
                                            {(sorts.total == 'none' ||
                                                sorts.total ==
                                                    'descending') && (
                                                <svg
                                                    viewBox="0 0 32 32"
                                                    focusable="false"
                                                    className="h-3 w-3 cursor-pointer"
                                                    onClick={() =>
                                                        sortHandler(
                                                            'total',
                                                            'descending'
                                                        )
                                                    }
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        clipRule="evenodd"
                                                        d="M16 22L6 12L7.4 10.6L16 19.2L24.6 10.6L26 12L16 22Z"
                                                        fill="currentColor"
                                                    ></path>
                                                </svg>
                                            )}
                                        </div>
                                    </div>
                                </th>
                                <th className="w-[15%] px-6 py-4">
                                    <div className="flex items-center">
                                        24h Vol
                                        <div className="ml-2 flex flex-col items-center">
                                            {(sorts.day == 'none' ||
                                                sorts.day == 'ascending') && (
                                                <svg
                                                    viewBox="0 0 32 32"
                                                    focusable="false"
                                                    className="h-3 w-3 cursor-pointer"
                                                    onClick={() =>
                                                        sortHandler(
                                                            'day',
                                                            'ascending'
                                                        )
                                                    }
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        clipRule="evenodd"
                                                        d="M16 10L26 20L24.6 21.4L16 12.8L7.4 21.4L6 20L16 10Z"
                                                        fill="currentColor"
                                                    ></path>
                                                </svg>
                                            )}
                                            {(sorts.day == 'none' ||
                                                sorts.day == 'descending') && (
                                                <svg
                                                    viewBox="0 0 32 32"
                                                    focusable="false"
                                                    className="h-3 w-3 cursor-pointer"
                                                    onClick={() =>
                                                        sortHandler(
                                                            'day',
                                                            'descending'
                                                        )
                                                    }
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        clipRule="evenodd"
                                                        d="M16 22L6 12L7.4 10.6L16 19.2L24.6 10.6L26 12L16 22Z"
                                                        fill="currentColor"
                                                    ></path>
                                                </svg>
                                            )}
                                        </div>
                                    </div>
                                </th>
                                <th className="w-[15%] px-6 py-4">
                                    <div className="flex items-center">
                                        24h Vol%
                                        <div className="ml-2 flex flex-col items-center">
                                            {(sorts.dayPercent == 'none' ||
                                                sorts.dayPercent ==
                                                    'ascending') && (
                                                <svg
                                                    viewBox="0 0 32 32"
                                                    focusable="false"
                                                    className="h-3 w-3 cursor-pointer"
                                                    onClick={() =>
                                                        sortHandler(
                                                            'dayPercent',
                                                            'ascending'
                                                        )
                                                    }
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        clipRule="evenodd"
                                                        d="M16 10L26 20L24.6 21.4L16 12.8L7.4 21.4L6 20L16 10Z"
                                                        fill="currentColor"
                                                    ></path>
                                                </svg>
                                            )}
                                            {(sorts.dayPercent == 'none' ||
                                                sorts.dayPercent ==
                                                    'descending') && (
                                                <svg
                                                    viewBox="0 0 32 32"
                                                    focusable="false"
                                                    className="h-3 w-3 cursor-pointer"
                                                    onClick={() =>
                                                        sortHandler(
                                                            'dayPercent',
                                                            'descending'
                                                        )
                                                    }
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        clipRule="evenodd"
                                                        d="M16 22L6 12L7.4 10.6L16 19.2L24.6 10.6L26 12L16 22Z"
                                                        fill="currentColor"
                                                    ></path>
                                                </svg>
                                            )}
                                        </div>
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody className="border border-dark-100 dark:border-0 dark:text-white">
                            {data.map((item: any, index: number) => (
                                <tr
                                    className="cursor-pointer border-b border-dark-100 transition duration-300 ease-in-out dark:border-dark-300 dark:bg-dark-400 hover:dark:bg-dark-300"
                                    onClick={() => goToCollection(item.addrs)}
                                    key={index}
                                >
                                    <th className="px-6 py-4">{index + 1}</th>
                                    <td className="whitespace-nowrap px-6 py-4">
                                        <div className="flex items-center">
                                            <Image
                                                className="h-10 w-10 rounded-full"
                                                src={
                                                    process.env
                                                        .NEXT_PUBLIC_SERVER_URL +
                                                    item.image
                                                }
                                                alt="collection"
                                                width={40}
                                                height={40}
                                            />
                                            <h3 className="ml-3 text-lg font-medium">
                                                {item.name}
                                            </h3>
                                        </div>
                                    </td>
                                    <td className="whitespace-nowrap px-6 py-4">
                                        <div className="text-sm">Floor</div>
                                        <div className="flex items-center">
                                            <svg
                                                viewBox="0 0 48 96"
                                                focusable="false"
                                                className="mr-1 h-5 w-2.5"
                                            >
                                                <path
                                                    d="M23.9932 8.91386L23.4688 10.6953V62.3843L23.9932 62.9075L47.9862 48.725L23.9932 8.91386Z"
                                                    fill="#767676"
                                                ></path>
                                                <path
                                                    d="M23.9936 8.91386L0 48.725L23.9936 62.9075V37.8191V8.91386Z"
                                                    fill="#8E8E8E"
                                                ></path>
                                                <path
                                                    d="M23.9914 67.4523L23.6958 67.8128V86.2251L23.9914 87.088L47.9991 53.2772L23.9914 67.4523Z"
                                                    fill="#5F5F5F"
                                                ></path>
                                                <path
                                                    d="M23.9936 87.088V67.4523L0 53.2772L23.9936 87.088Z"
                                                    fill="#8E8E8E"
                                                ></path>
                                                <path
                                                    d="M23.9937 62.9066L47.9867 48.7242L23.9937 37.8183V62.9066Z"
                                                    fill="#5F5F5F"
                                                ></path>
                                                <path
                                                    d="M0 48.7242L23.9936 62.9066V37.8183L0 48.7242Z"
                                                    fill="#767676"
                                                ></path>
                                            </svg>
                                            <span className="font-medium">
                                                {item.floorOrder &&
                                                    item.floorOrder.price /
                                                        1000000000000000000}
                                            </span>
                                        </div>
                                    </td>
                                    <td className="whitespace-nowrap px-6 py-4">
                                        <div className="text-sm">Total Vol</div>
                                        <div className="flex items-center">
                                            <svg
                                                viewBox="0 0 48 96"
                                                focusable="false"
                                                className="mr-1 h-5 w-2.5"
                                            >
                                                <path
                                                    d="M23.9932 8.91386L23.4688 10.6953V62.3843L23.9932 62.9075L47.9862 48.725L23.9932 8.91386Z"
                                                    fill="#767676"
                                                ></path>
                                                <path
                                                    d="M23.9936 8.91386L0 48.725L23.9936 62.9075V37.8191V8.91386Z"
                                                    fill="#8E8E8E"
                                                ></path>
                                                <path
                                                    d="M23.9914 67.4523L23.6958 67.8128V86.2251L23.9914 87.088L47.9991 53.2772L23.9914 67.4523Z"
                                                    fill="#5F5F5F"
                                                ></path>
                                                <path
                                                    d="M23.9936 87.088V67.4523L0 53.2772L23.9936 87.088Z"
                                                    fill="#8E8E8E"
                                                ></path>
                                                <path
                                                    d="M23.9937 62.9066L47.9867 48.7242L23.9937 37.8183V62.9066Z"
                                                    fill="#5F5F5F"
                                                ></path>
                                                <path
                                                    d="M0 48.7242L23.9936 62.9066V37.8183L0 48.7242Z"
                                                    fill="#767676"
                                                ></path>
                                            </svg>
                                            <span className="font-medium">
                                                {item.volume &&
                                                    (
                                                        parseInt(
                                                            item.volume
                                                                .volumeAll
                                                        ) / 1000000000000000000
                                                    ).toFixed(2)}
                                            </span>
                                        </div>
                                    </td>
                                    <td className="whitespace-nowrap px-6 py-4">
                                        <div className="text-sm">24h Vol</div>
                                        <div className="flex items-center">
                                            <svg
                                                viewBox="0 0 48 96"
                                                focusable="false"
                                                className="mr-1 h-5 w-2.5"
                                            >
                                                <path
                                                    d="M23.9932 8.91386L23.4688 10.6953V62.3843L23.9932 62.9075L47.9862 48.725L23.9932 8.91386Z"
                                                    fill="#767676"
                                                ></path>
                                                <path
                                                    d="M23.9936 8.91386L0 48.725L23.9936 62.9075V37.8191V8.91386Z"
                                                    fill="#8E8E8E"
                                                ></path>
                                                <path
                                                    d="M23.9914 67.4523L23.6958 67.8128V86.2251L23.9914 87.088L47.9991 53.2772L23.9914 67.4523Z"
                                                    fill="#5F5F5F"
                                                ></path>
                                                <path
                                                    d="M23.9936 87.088V67.4523L0 53.2772L23.9936 87.088Z"
                                                    fill="#8E8E8E"
                                                ></path>
                                                <path
                                                    d="M23.9937 62.9066L47.9867 48.7242L23.9937 37.8183V62.9066Z"
                                                    fill="#5F5F5F"
                                                ></path>
                                                <path
                                                    d="M0 48.7242L23.9936 62.9066V37.8183L0 48.7242Z"
                                                    fill="#767676"
                                                ></path>
                                            </svg>
                                            <span className="font-medium">
                                                {item.volume &&
                                                    (
                                                        parseInt(
                                                            item.volume
                                                                .volume24h
                                                        ) / 1000000000000000000
                                                    ).toFixed(2)}
                                            </span>
                                        </div>
                                    </td>
                                    <td className="whitespace-nowrap px-6 py-4">
                                        <div className="text-sm">24h Vol %</div>
                                        <div className="flex items-center">
                                            {item.volume &&
                                            item.volume.change24h < 0 ? (
                                                <span className="flex items-center font-medium text-red-700">
                                                    {item.volume &&
                                                        Math.round(
                                                            item.volume
                                                                .change24h * 100
                                                        ) / 100}
                                                    %
                                                    <svg
                                                        viewBox="0 0 32 32"
                                                        focusable="false"
                                                        className="ml-2 h-4 w-4"
                                                    >
                                                        <path
                                                            fillRule="evenodd"
                                                            clipRule="evenodd"
                                                            d="M24.59 16.59L17 24.17V2H15V24.17L7.41 16.59L6 18L16 28L26 18L24.59 16.59Z"
                                                            fill="currentColor"
                                                        ></path>
                                                    </svg>
                                                </span>
                                            ) : (
                                                <span className="flex items-center font-medium text-green-700">
                                                    {item.volume &&
                                                        Math.round(
                                                            item.volume
                                                                .change24h * 100
                                                        ) / 100}
                                                    %
                                                    <svg
                                                        viewBox="0 0 32 32"
                                                        focusable="false"
                                                        className="ml-2 h-4 w-4"
                                                    >
                                                        <path
                                                            fillRule="evenodd"
                                                            clipRule="evenodd"
                                                            d="M16 4L6 14L7.41 15.41L15 7.83V30H17V7.83L24.59 15.41L26 14L16 4Z"
                                                            fill="currentColor"
                                                        ></path>
                                                    </svg>
                                                </span>
                                            )}
                                        </div>
                                    </td>
                                </tr>
                            ))}
                            {isLoading &&
                                new Array(10).fill(10).map((item, index) => (
                                    <tr
                                        className="cursor-pointer border-b border-dark-100 transition duration-300 ease-in-out dark:border-dark-300 dark:bg-dark-400 hover:dark:bg-dark-300"
                                        key={index}
                                    >
                                        <th className="px-6 py-4">
                                            <div className="h-4 w-4 animate-pulse rounded-sm bg-gray-600"></div>
                                        </th>
                                        <td className="whitespace-nowrap px-6 py-4">
                                            <div className="flex items-center">
                                                <div className="h-8 w-8 animate-pulse rounded-sm bg-gray-600"></div>
                                                <h3 className="ml-3 text-lg font-medium">
                                                    <div className="h-4 w-32 animate-pulse rounded-sm bg-gray-600"></div>
                                                </h3>
                                            </div>
                                        </td>
                                        <td className="whitespace-nowrap px-6 py-4">
                                            <div className="text-sm">
                                                <div className="mb-2 h-4 w-8 animate-pulse rounded-sm bg-gray-600"></div>
                                            </div>
                                            <div className="flex items-center">
                                                <div className="h-4 w-12 animate-pulse rounded-sm bg-gray-600"></div>
                                            </div>
                                        </td>
                                        <td className="whitespace-nowrap px-6 py-4">
                                            <div className="text-sm">
                                                <div className="mb-2 h-4 w-8 animate-pulse rounded-sm bg-gray-600"></div>
                                            </div>
                                            <div className="flex items-center">
                                                <div className="h-4 w-12 animate-pulse rounded-sm bg-gray-600"></div>
                                            </div>
                                        </td>
                                        <td className="whitespace-nowrap px-6 py-4">
                                            <div className="text-sm">
                                                <div className="mb-2 h-4 w-8 animate-pulse rounded-sm bg-gray-600"></div>
                                            </div>
                                            <div className="flex items-center">
                                                <div className="h-4 w-12 animate-pulse rounded-sm bg-gray-600"></div>
                                            </div>
                                        </td>
                                        <td className="whitespace-nowrap px-6 py-4">
                                            <div className="text-sm">
                                                <div className="mb-2 h-4 w-8 animate-pulse rounded-sm bg-gray-600"></div>
                                            </div>
                                            <div className="flex items-center">
                                                <div className="h-4 w-12 animate-pulse rounded-sm bg-gray-600"></div>
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                        </tbody>
                    </table>
                </div>
                <div className="container mb-8 text-center">
                    {hasMore && (
                        <button
                            className="mx-auto mb-8 border-0 bg-dark-400 bg-opacity-50 px-4 py-2 font-medium text-white hover:bg-dark-300"
                            onClick={loadMoreHandler}
                        >
                            Load More
                        </button>
                    )}
                </div>
            </main>
        </div>
    )
}

export default Collection
