import type { NextPage } from 'next'
import Head from 'next/head'
import {useState, useEffect } from 'react';
import { ethers } from 'ethers'
import CoinbaseWalletSDK from "@coinbase/wallet-sdk"
import Web3Modal from "web3modal";
import {abi, contractAddress} from '~/contract';

type connectorOptions = {
  appName: string;
  networkUrl: string;
  chainId: number | undefined;
};


const providerOptions = {
  "custom-walletlink": {
    display: {
      logo: "https://play-lh.googleusercontent.com/PjoJoG27miSglVBXoXrxBSLveV6e3EeBPpNY55aiUUBM9Q1RCETKCOqdOkX2ZydqVf0",
      name: "Coinbase",
      description: "Connect to Coinbase Wallet (not Coinbase App)",
    },
    options: {
      appName: "Coinbase", // Your app name
      networkUrl: "https://rpc.ankr.com/avalanche_fuji-c",
      chainId: 43113,
    },
    package: CoinbaseWalletSDK,
    connector: async (_: null, options: connectorOptions) => {
      const { appName, networkUrl, chainId } = options;
      const walletLink = new CoinbaseWalletSDK({
        appName,
      });
      const provider = walletLink.makeWeb3Provider(networkUrl, chainId);
      await provider.enable();
      return provider;
    },
  }
};

const Rewards: NextPage = () => {

    const [volume, setVolume]=useState("");
    const [balance, setBalance]=useState("");

    useEffect(()=>{showVolume();},);
    useEffect(()=>{showBalance();},);

    async function showBalance(){

      const web3Modal = new Web3Modal({
        providerOptions // required
      });
      const provider = await web3Modal.connect();
      const library = new ethers.providers.Web3Provider(provider);
      const signer = library.getSigner();
      const contract = new ethers.Contract(contractAddress, abi, signer);
      const walletAddress=await signer.getAddress();
      try{
      const transaction = await contract.getBalance(walletAddress);
      setBalance(transaction);}
      catch(err){
        setBalance("0");
      }
    }



    async function showVolume(){

      const web3Modal = new Web3Modal({
        providerOptions // required
      });
      const provider = await web3Modal.connect();
      const library = new ethers.providers.Web3Provider(provider);
      const signer = library.getSigner();
      const contract = new ethers.Contract(contractAddress, abi, signer);
      const walletAddress=await signer.getAddress();
      const transaction = await contract.getVolumes(walletAddress);
      if (transaction.length==0){setVolume("0")}
      else{const sum = transaction.reduce((partialSum : any, a : any) => partialSum + a, 0);
            setVolume(sum);}
    }

    return (
        <div>
            <Head>
                <title>Jaypigs rewards page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="my-8 min-h-screen py-32 text-center">
                <div className="w-100 mx-auto max-w-lg">
                    <h2 className="mb-8 text-[35px] font-medium">Dashboard</h2>
                    <div className="grid gap-2 sm:grid-cols-3">
                        <div className="mb-8">
                            <h3 className="mb-2 text-lg font-medium">
                                Sales Volume
                            </h3>
                            <h4>{volume}</h4>
                        </div>
                        <div className="mb-8">
                            <h3 className="mb-2 text-lg font-medium">
                                Balance <br /> {balance}
                            </h3>
                            <button className="rounded-full border-0 bg-dark-500 bg-opacity-50 px-4 py-2 font-medium text-white hover:bg-dark-500 dark:bg-white dark:text-black">
                                Claim
                            </button>
                        </div>
                        <div className="mb-8">
                            <h3 className="mb-2 text-lg font-medium">
                                Farm your Volume
                            </h3>
                            <button className="rounded-full border-0 bg-dark-500 bg-opacity-50 px-4 py-2 font-medium text-white hover:bg-dark-500 dark:bg-white dark:text-black">
                                Coming Soon
                            </button>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Rewards
